version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
        environment:
          PG_TEST_USERNAME: root
          PG_TEST_DATABASE: circle_test
          PG_TEST_HOST: localhost
          API_VERSION: v1
          HYDRA_DASHBOARD_CLIENT_ID: hydra-dashboard-test
          HYDRA_DASHBOARD_CLIENT_SECRET: hydra-dashboard-secret-test
          HYDRA_PUBLIC_URL: https://hydra.test:9000
          HYDRA_ADMIN_URL: https://hydra.test:9001
          HYDRA_CALLBACK_URI: http://hydra.test:3000/callback
          HYDRA_CONSENT_URL: http://hydra.test:3000

      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
      - run: npm test

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
